### ISSUE TITLE
Social Settings

### ISSUE THREAD

**Issue by JoyJulianGomes** [chrisbobbe/jekyll-theme-prologue#15]
First of all, thanks for the theme.

**The Issue:**
I have set up the social links in the _config.yml as
`github_url: "www.github.com/****"`
But in the final output the link transformed to _https://username.github.io/projectname/www.github.com/****_

**Note:**
In _config.yml url and baseurl are set as - 
```
baseurl: "/projectname"
url: "username.github.io"
```
**Update:**
The embedded social media url seems correct but when mouse hover or click event occurs they change to _"https://username.github.io/projectname/social_media_url"_
![untitled](https://user-images.githubusercontent.com/22003711/39393987-bcfd3dae-4aed-11e8-8bfb-5430f18c1c5a.png)

**Comment by ahsen1402** [comment]
any solutions on this, i seem to have the same issue.

**Comment by JoyJulianGomes** [comment]
@Drakmyth thanks!!
