### ISSUE TITLE
Github social_icon

### ISSUE THREAD

**Issue by deltronzero94** [chrisbobbe/jekyll-theme-prologue#4]
Hello, I noticed when I add the Github url in the _config.yml, it would not appear as one of the social icons. I ended up figuring out that it is not in the social_icons.html, which is the reason why it does not appear as an icon. Not sure if this was done on purpose or by accident. Just wanted to let you know.

**Comment by chrisbobbe** [comment]
Thank you, I hadn't noticed that! I fixed it by adding it to social_icons.html, and pushed it to GitHub and the theme gem.
